### PR TITLE
Fix LoadBalancerRouting Networkref population

### LINKED ISSUE #557: Set NetworkRef.UID in the LBRouting object
**Describe the bug**
LBRouting doesn't have NetworkRef set in it. 

**To Reproduce**
Create an LB object and in turn LBR object. 

**Expected behavior**
To have NetworkRef always set.

### PR DESCRIPTION
**Pull request by hardikdr**
# Proposed Changes
Fixing the missing NetworkRef in loadbalancerrouting. 

Fixes #557

### CODE REVIEW

File: onmetal-controller-manager/controllers/networking/loadbalancer_controller.go [hunk 1]
```diff
@@ -85,8 +86,15 @@ func (r *LoadBalancerReconciler) reconcile(ctx context.Context, log logr.Logger,
 	}
 	log.V(1).Info("Successfully found destinations", "Destinations", destinations)
 
+	log.V(1).Info("Finding network")
+	network, err := r.findNetwork(ctx, log, loadBalancer)
+	if err != nil {
+		return ctrl.Result{}, fmt.Errorf("error finding network: %w", err)
```
Comment (afritzler) [inline onmetal-controller-manager/controllers/networking/loadbalancer_controller.go:92]: We might want to print out which network we wanted to find.

File: onmetal-controller-manager/controllers/networking/loadbalancer_controller.go [hunk 2]
```diff
@@ -115,7 +123,15 @@ func (r *LoadBalancerReconciler) findDestinations(ctx context.Context, log logr.
 	return destinations, nil
 }
 
-func (r *LoadBalancerReconciler) applyRouting(ctx context.Context, loadBalancer *networkingv1alpha1.LoadBalancer, destinations []commonv1alpha1.LocalUIDReference) error {
+func (r *LoadBalancerReconciler) findNetwork(ctx context.Context, log logr.Logger, loadBalancer *networkingv1alpha1.LoadBalancer) (*networkingv1alpha1.Network, error) {
+	network := &networkingv1alpha1.Network{}
+	if err := r.Get(ctx, types.NamespacedName{Name: loadBalancer.Spec.NetworkRef.Name, Namespace: loadBalancer.Namespace}, network); err != nil {
+		return nil, fmt.Errorf("error getting network: %w", err)
```
Comment (afritzler) [inline onmetal-controller-manager/controllers/networking/loadbalancer_controller.go:129]: Same as above.

File: onmetal-controller-manager/controllers/networking/loadbalancer_controller.go [hunk 3]
```diff
@@ -115,7 +123,15 @@ func (r *LoadBalancerReconciler) findDestinations(ctx context.Context, log logr.
 	return destinations, nil
 }
 
-func (r *LoadBalancerReconciler) applyRouting(ctx context.Context, loadBalancer *networkingv1alpha1.LoadBalancer, destinations []commonv1alpha1.LocalUIDReference) error {
+func (r *LoadBalancerReconciler) findNetwork(ctx context.Context, log logr.Logger, loadBalancer *networkingv1alpha1.LoadBalancer) (*networkingv1alpha1.Network, error) {
```
Comment (afritzler) [inline onmetal-controller-manager/controllers/networking/loadbalancer_controller.go:126]: Can we call this method `getNetwork` because that is what essentially is happening here.

**Review by afritzler — CHANGES_REQUESTED** [review]

File: onmetal-controller-manager/controllers/networking/loadbalancer_controller.go (hunk 1 above)
Comment (hardikdr) [reply onmetal-controller-manager/controllers/networking/loadbalancer_controller.go]: done

File: onmetal-controller-manager/controllers/networking/loadbalancer_controller.go (hunk 3 above)
Comment (hardikdr) [reply onmetal-controller-manager/controllers/networking/loadbalancer_controller.go]: done

File: onmetal-controller-manager/controllers/networking/loadbalancer_controller.go (hunk 2 above)
Comment (hardikdr) [reply onmetal-controller-manager/controllers/networking/loadbalancer_controller.go]: done
